// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmg3O5CSntHRljBl1Usm0CITrPvJO7T2Y',
    appId: '1:491560581247:web:729eb481742d40cf11274a',
    messagingSenderId: '491560581247',
    projectId: 'raydeeplink',
    authDomain: 'raydeeplink.firebaseapp.com',
    storageBucket: 'raydeeplink.appspot.com',
    measurementId: 'G-19PS9ZCWKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc21rH9X6rphevD1h2drCPF7wef48_P_o',
    appId: '1:491560581247:android:518973564c3d75db11274a',
    messagingSenderId: '491560581247',
    projectId: 'raydeeplink',
    storageBucket: 'raydeeplink.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2-kX_xOgkzI5n-MuNakVzH6HOI9640Eg',
    appId: '1:491560581247:ios:acd8527f8e34e0f811274a',
    messagingSenderId: '491560581247',
    projectId: 'raydeeplink',
    storageBucket: 'raydeeplink.appspot.com',
    androidClientId: '491560581247-9a7vfc23mvb2utqf4pls0bvk0hreg62s.apps.googleusercontent.com',
    iosClientId: '491560581247-mbnt2bidv9paa05dvdr18pt1dveq1stq.apps.googleusercontent.com',
    iosBundleId: 'com.example.deeplink',
  );
}
